package net.entellitrak.aea.du.service;

import java.io.InputStream;

import net.entellitrak.aea.du.service.organizationalHierarchy.IOrganizationalHierarchyImportResult;

/**
 * This interface describes classes which implement functionality related to moving Organizational Hierarchy from one
 * site to another.
 *
 * @author zachary.miller
 */
public interface IOrganizationalHierarchyMigrationService {

    /**
     * This method exports Organizational Hierarchy data to an input stream in the same format as the
     * DU - Page - Organizational Unit Export page. This method can be used as part of an automated build script so that
     * the AE does not need to manually run the DU - Page - Organizational Unit Export page each time a deployment
     * package must be built.
     *
     * @return an input stream containing the Organizational Hierarchy data.
     *          The caller of this method is responsible for closing the stream.
     * @throws Exception If anything went wrong
     *
     * @see #importFromStream(InputStream)
     */
	// Suppress warning about throwing generic exception to maintain backwards compatibility.
	@SuppressWarnings("java:S112")
    InputStream exportToStream() throws Exception;


    /**
     * Imports Organizational Hierarchies into this system. Accepts a file as an input stream which has the format generated
     * by {@link #exportToStream()}.
     *
     * @param orgHierarchyStream raw input stream data which is generated by the export tool.
     *          This method currently does not close this stream.
     * @return the result of the import
     * @throws Exception If anything went wrong
     */
	// Suppress warning about throwing generic exception to maintain backwards compatibility.
	@SuppressWarnings("java:S112")
    IOrganizationalHierarchyImportResult importFromStream(InputStream orgHierarchyStream) throws Exception;
}
